name: regal_service_d_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.11+12

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename:
  get:
  google_fonts:
  cached_network_image:
  carousel_slider:
  smooth_page_indicator:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  flutter_local_notifications:
  geocoding:
  geolocator:
  location:
  lottie:
  shimmer:
  intl:
  flutter_rating_bar:
  flutter_vector_icons:
  flutter_screenutil:
  google_maps_flutter:
  flutter_google_places:
  http:
  url_launcher:
  image_picker:
  flutter_ringtone_player:
  rxdart:
  vibration:
  logger:
  google_maps_place_picker_mb:
  photo_view:
  flutter_animate:
  cloud_functions:
  share_plus:
  pdf:
  printing:
  multi_select_flutter:
  file_picker:
  excel:
  open_file:
  csv:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

#for app logo
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_new_logo.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/
    - assets/noti.mp3

  fonts:
    - family: Universe
      fonts:
        - asset: assets/font/UniversRegular.ttf
        - asset: assets/font/UniversBold.ttf
